version: '2.3'

services:
  mysqldb:
    image: mysql:5
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - net

  rabbit:
    image: rabbitmq:3.10.7-management
    container_name: rabbitMQ
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net
  api:
    build: .
    container_name: ms-api
    ports:
      - "8080:8080"
      - "3306:3306"
    links:
      - mysqldb:mysqldb
    depends_on:
      - rabbit
      - mysqldb
    networks:
      - net

networks:
  net:
    driver: host
